package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUsers<M extends BaseAppUsers<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 姓名
	 */
	public void setLtRealName(java.lang.String ltRealName) {
		set("lt_real_name", ltRealName);
	}

	/**
	 * 姓名
	 */
	public java.lang.String getLtRealName() {
		return getStr("lt_real_name");
	}

	/**
	 * 身份证号
	 */
	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}

	/**
	 * 身份证号
	 */
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	/**
	 * 手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	/**
	 * 手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 性别
	 */
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	/**
	 * 性别
	 */
	public java.lang.String getSex() {
		return getStr("sex");
	}

	/**
	 * 名族
	 */
	public void setMingzu(java.lang.String mingzu) {
		set("mingzu", mingzu);
	}

	/**
	 * 名族
	 */
	public java.lang.String getMingzu() {
		return getStr("mingzu");
	}

	/**
	 * 年度累计积分
	 */
	public void setTotalPoints(java.lang.Integer totalPoints) {
		set("total_points", totalPoints);
	}

	/**
	 * 年度累计积分
	 */
	public java.lang.Integer getTotalPoints() {
		return getInt("total_points");
	}

	/**
	 * 现有积分
	 */
	public void setCurrentPoints(java.lang.Integer currentPoints) {
		set("current_points", currentPoints);
	}

	/**
	 * 现有积分
	 */
	public java.lang.Integer getCurrentPoints() {
		return getInt("current_points");
	}

	/**
	 * 微信unionID
	 */
	public void setWxUnionId(java.lang.String wxUnionId) {
		set("wx_union_id", wxUnionId);
	}

	/**
	 * 微信unionID
	 */
	public java.lang.String getWxUnionId() {
		return getStr("wx_union_id");
	}

	/**
	 * 微信openID
	 */
	public void setWxOpenId(java.lang.String wxOpenId) {
		set("wx_open_id", wxOpenId);
	}

	/**
	 * 微信openID
	 */
	public java.lang.String getWxOpenId() {
		return getStr("wx_open_id");
	}

	/**
	 * 微信昵称
	 */
	public void setWxNickName(java.lang.String wxNickName) {
		set("wx_nick_name", wxNickName);
	}

	/**
	 * 微信昵称
	 */
	public java.lang.String getWxNickName() {
		return getStr("wx_nick_name");
	}

	/**
	 * 微信头像url
	 */
	public void setWxAvatarurl(java.lang.String wxAvatarurl) {
		set("wx_avatarUrl", wxAvatarurl);
	}

	/**
	 * 微信头像url
	 */
	public java.lang.String getWxAvatarurl() {
		return getStr("wx_avatarUrl");
	}

	/**
	 * 微信国家
	 */
	public void setWxCountry(java.lang.String wxCountry) {
		set("wx_country", wxCountry);
	}

	/**
	 * 微信国家
	 */
	public java.lang.String getWxCountry() {
		return getStr("wx_country");
	}

	/**
	 * 微信所在省
	 */
	public void setWxProvince(java.lang.String wxProvince) {
		set("wx_province", wxProvince);
	}

	/**
	 * 微信所在省
	 */
	public java.lang.String getWxProvince() {
		return getStr("wx_province");
	}

	/**
	 * 微信所在城市
	 */
	public void setWxCity(java.lang.String wxCity) {
		set("wx_city", wxCity);
	}

	/**
	 * 微信所在城市
	 */
	public java.lang.String getWxCity() {
		return getStr("wx_city");
	}

	/**
	 * 微信所用语言
	 */
	public void setWxLanguage(java.lang.String wxLanguage) {
		set("wx_language", wxLanguage);
	}

	/**
	 * 微信所用语言
	 */
	public java.lang.String getWxLanguage() {
		return getStr("wx_language");
	}

	/**
	 * 某天首次打开微信首页时记录，一天只记录一次
	 */
	public void setLastLoginTime(java.lang.String lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}

	/**
	 * 某天首次打开微信首页时记录，一天只记录一次
	 */
	public java.lang.String getLastLoginTime() {
		return getStr("last_login_time");
	}

	/**
	 * 累计登录次数
	 */
	public void setLoginCount(java.lang.String loginCount) {
		set("login_count", loginCount);
	}

	/**
	 * 累计登录次数
	 */
	public java.lang.String getLoginCount() {
		return getStr("login_count");
	}

	/**
	 * 省(住址)
	 */
	public void setAddressProvince(java.lang.String addressProvince) {
		set("address_province", addressProvince);
	}

	/**
	 * 省(住址)
	 */
	public java.lang.String getAddressProvince() {
		return getStr("address_province");
	}

	/**
	 * 市(住址)
	 */
	public void setAddressCity(java.lang.String addressCity) {
		set("address_city", addressCity);
	}

	/**
	 * 市(住址)
	 */
	public java.lang.String getAddressCity() {
		return getStr("address_city");
	}

	/**
	 * 区县(住址),关联组织机构ID
	 */
	public void setAddressArea(java.lang.String addressArea) {
		set("address_area", addressArea);
	}

	/**
	 * 区县(住址),关联组织机构ID
	 */
	public java.lang.String getAddressArea() {
		return getStr("address_area");
	}

	/**
	 * 街道(住址),关联组织机构ID
	 */
	public void setAddressStreet(java.lang.String addressStreet) {
		set("address_street", addressStreet);
	}

	/**
	 * 街道(住址),关联组织机构ID
	 */
	public java.lang.String getAddressStreet() {
		return getStr("address_street");
	}

	/**
	 * 社区(住址),关联组织机构ID
	 */
	public void setAddressCommunity(java.lang.String addressCommunity) {
		set("address_community", addressCommunity);
	}

	/**
	 * 社区(住址),关联组织机构ID
	 */
	public java.lang.String getAddressCommunity() {
		return getStr("address_community");
	}

	/**
	 * 小区(住址),关联 社区小区楼院 ID
	 */
	public void setAddressQuartersId(java.lang.String addressQuartersId) {
		set("address_quarters_id", addressQuartersId);
	}

	/**
	 * 小区(住址),关联 社区小区楼院 ID
	 */
	public java.lang.String getAddressQuartersId() {
		return getStr("address_quarters_id");
	}

	/**
	 * 楼号(住址)
	 */
	public void setAddressFloor(java.lang.String addressFloor) {
		set("address_floor", addressFloor);
	}

	/**
	 * 楼号(住址)
	 */
	public java.lang.String getAddressFloor() {
		return getStr("address_floor");
	}

	/**
	 * 单元号(住址)
	 */
	public void setAddressUnit(java.lang.String addressUnit) {
		set("address_unit", addressUnit);
	}

	/**
	 * 单元号(住址)
	 */
	public java.lang.String getAddressUnit() {
		return getStr("address_unit");
	}

	/**
	 * 门牌号(住址)
	 */
	public void setAddressNumber(java.lang.String addressNumber) {
		set("address_number", addressNumber);
	}

	/**
	 * 门牌号(住址)
	 */
	public java.lang.String getAddressNumber() {
		return getStr("address_number");
	}

	/**
	 * 所属工会id
	 */
	public void setLabourUnionId(java.lang.String labourUnionId) {
		set("labour_union_id", labourUnionId);
	}

	/**
	 * 所属工会id
	 */
	public java.lang.String getLabourUnionId() {
		return getStr("labour_union_id");
	}

	/**
	 * 所属工会名称
	 */
	public void setLabourUnionName(java.lang.String labourUnionName) {
		set("labour_union_name", labourUnionName);
	}

	/**
	 * 所属工会名称
	 */
	public java.lang.String getLabourUnionName() {
		return getStr("labour_union_name");
	}

	/**
	 * 所属社区id
	 */
	public void setCommunityId(java.lang.String communityId) {
		set("community_id", communityId);
	}

	/**
	 * 所属社区id
	 */
	public java.lang.String getCommunityId() {
		return getStr("community_id");
	}

	/**
	 * 所属社区名称
	 */
	public void setCommunityName(java.lang.String communityName) {
		set("community_name", communityName);
	}

	/**
	 * 所属社区名称
	 */
	public java.lang.String getCommunityName() {
		return getStr("community_name");
	}

	/**
	 * 是否注册
	 */
	public void setIsRegister(java.lang.String isRegister) {
		set("is_register", isRegister);
	}

	/**
	 * 是否注册
	 */
	public java.lang.String getIsRegister() {
		return getStr("is_register");
	}

	/**
	 * 证件照
	 */
	public void setIdPhoto(java.lang.String idPhoto) {
		set("id_photo", idPhoto);
	}

	/**
	 * 证件照
	 */
	public java.lang.String getIdPhoto() {
		return getStr("id_photo");
	}

	/**
	 * 签名照
	 */
	public void setAutographImg(java.lang.String autographImg) {
		set("autograph_img", autographImg);
	}

	/**
	 * 签名照
	 */
	public java.lang.String getAutographImg() {
		return getStr("autograph_img");
	}

	public void setSpare1(java.lang.String spare1) {
		set("spare1", spare1);
	}

	public java.lang.String getSpare1() {
		return getStr("spare1");
	}

	public void setSpare2(java.lang.String spare2) {
		set("spare2", spare2);
	}

	public java.lang.String getSpare2() {
		return getStr("spare2");
	}

	public void setSpare3(java.lang.String spare3) {
		set("spare3", spare3);
	}

	public java.lang.String getSpare3() {
		return getStr("spare3");
	}

	public void setSpare4(java.lang.String spare4) {
		set("spare4", spare4);
	}

	public java.lang.String getSpare4() {
		return getStr("spare4");
	}

	public void setSpare5(java.lang.String spare5) {
		set("spare5", spare5);
	}

	public java.lang.String getSpare5() {
		return getStr("spare5");
	}
	
}
