package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUsers<M extends BaseAppUsers<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 昵称
	 */
	public void setLtNickName(java.lang.String ltNickName) {
		set("lt_nick_name", ltNickName);
	}
	
	/**
	 * 昵称
	 */
	public java.lang.String getLtNickName() {
		return getStr("lt_nick_name");
	}
	
	/**
	 * 用户名
	 */
	public void setLtUserName(java.lang.String ltUserName) {
		set("lt_user_name", ltUserName);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getLtUserName() {
		return getStr("lt_user_name");
	}
	
	/**
	 * 同步id
	 */
	public void setLtSyncId(java.lang.String ltSyncId) {
		set("lt_sync_id", ltSyncId);
	}
	
	/**
	 * 同步id
	 */
	public java.lang.String getLtSyncId() {
		return getStr("lt_sync_id");
	}
	
	/**
	 * 姓名
	 */
	public void setLtRealName(java.lang.String ltRealName) {
		set("lt_real_name", ltRealName);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getLtRealName() {
		return getStr("lt_real_name");
	}
	
	/**
	 * 隶属党组织的名称
	 */
	public void setLtOrgName(java.lang.String ltOrgName) {
		set("lt_org_name", ltOrgName);
	}
	
	/**
	 * 隶属党组织的名称
	 */
	public java.lang.String getLtOrgName() {
		return getStr("lt_org_name");
	}
	
	/**
	 * 隶属党组织的同步ID
	 */
	public void setLtOrgSyncId(java.lang.String ltOrgSyncId) {
		set("lt_org_sync_id", ltOrgSyncId);
	}
	
	/**
	 * 隶属党组织的同步ID
	 */
	public java.lang.String getLtOrgSyncId() {
		return getStr("lt_org_sync_id");
	}
	
	/**
	 * 所属社区id
	 */
	public void setCommunityId(java.lang.String communityId) {
		set("community_id", communityId);
	}
	
	/**
	 * 所属社区id
	 */
	public java.lang.String getCommunityId() {
		return getStr("community_id");
	}
	
	/**
	 * 所属社区名称
	 */
	public void setCommunityName(java.lang.String communityName) {
		set("community_name", communityName);
	}
	
	/**
	 * 所属社区名称
	 */
	public java.lang.String getCommunityName() {
		return getStr("community_name");
	}
	
	/**
	 * 年度累计积分
	 */
	public void setTotalPoints(java.lang.Double totalPoints) {
		set("total_points", totalPoints);
	}
	
	/**
	 * 年度累计积分
	 */
	public java.lang.Double getTotalPoints() {
		return getDouble("total_points");
	}
	
	/**
	 * 现有积分
	 */
	public void setCurrentPoints(java.lang.Double currentPoints) {
		set("current_points", currentPoints);
	}
	
	/**
	 * 现有积分
	 */
	public java.lang.Double getCurrentPoints() {
		return getDouble("current_points");
	}
	
	/**
	 * （0为党员，1为组织，2为群众）
	 */
	public void setLtAccountType(java.lang.String ltAccountType) {
		set("lt_account_type", ltAccountType);
	}
	
	/**
	 * （0为党员，1为组织，2为群众）
	 */
	public java.lang.String getLtAccountType() {
		return getStr("lt_account_type");
	}
	
	/**
	 * 微信unionID
	 */
	public void setWxUnionId(java.lang.String wxUnionId) {
		set("wx_union_id", wxUnionId);
	}
	
	/**
	 * 微信unionID
	 */
	public java.lang.String getWxUnionId() {
		return getStr("wx_union_id");
	}
	
	/**
	 * 微信openID
	 */
	public void setWxOpenId(java.lang.String wxOpenId) {
		set("wx_open_id", wxOpenId);
	}
	
	/**
	 * 微信openID
	 */
	public java.lang.String getWxOpenId() {
		return getStr("wx_open_id");
	}
	
	/**
	 * 身份证号
	 */
	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}
	
	/**
	 * 身份证号
	 */
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}
	
	/**
	 * 手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 性别
	 */
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	/**
	 * 性别
	 */
	public java.lang.String getSex() {
		return getStr("sex");
	}
	
	/**
	 * 微信昵称
	 */
	public void setWxNickName(java.lang.String wxNickName) {
		set("wx_nick_name", wxNickName);
	}
	
	/**
	 * 微信昵称
	 */
	public java.lang.String getWxNickName() {
		return getStr("wx_nick_name");
	}
	
	/**
	 * 微信头像url
	 */
	public void setWxAvatarurl(java.lang.String wxAvatarurl) {
		set("wx_avatarUrl", wxAvatarurl);
	}
	
	/**
	 * 微信头像url
	 */
	public java.lang.String getWxAvatarurl() {
		return getStr("wx_avatarUrl");
	}
	
	/**
	 * 微信所在国家
	 */
	public void setWxCountry(java.lang.String wxCountry) {
		set("wx_country", wxCountry);
	}
	
	/**
	 * 微信所在国家
	 */
	public java.lang.String getWxCountry() {
		return getStr("wx_country");
	}
	
	/**
	 * 微信所在省
	 */
	public void setWxProvince(java.lang.String wxProvince) {
		set("wx_province", wxProvince);
	}
	
	/**
	 * 微信所在省
	 */
	public java.lang.String getWxProvince() {
		return getStr("wx_province");
	}
	
	/**
	 * 微信所在城市
	 */
	public void setWxCity(java.lang.String wxCity) {
		set("wx_city", wxCity);
	}
	
	/**
	 * 微信所在城市
	 */
	public java.lang.String getWxCity() {
		return getStr("wx_city");
	}
	
	/**
	 * 微信所用语言
	 */
	public void setWxLanguage(java.lang.String wxLanguage) {
		set("wx_language", wxLanguage);
	}
	
	/**
	 * 微信所用语言
	 */
	public java.lang.String getWxLanguage() {
		return getStr("wx_language");
	}
	
	/**
	 * 某天首次打开微信首页时记录，一天只记录一次
	 */
	public void setLastLoginTime(java.lang.String lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	/**
	 * 某天首次打开微信首页时记录，一天只记录一次
	 */
	public java.lang.String getLastLoginTime() {
		return getStr("last_login_time");
	}
	
	/**
	 * 累计登录次数
	 */
	public void setLoginCount(java.lang.String loginCount) {
		set("login_count", loginCount);
	}
	
	/**
	 * 累计登录次数
	 */
	public java.lang.String getLoginCount() {
		return getStr("login_count");
	}
	
	/**
	 * 省(住址)
	 */
	public void setAddressProvince(java.lang.String addressProvince) {
		set("address_province", addressProvince);
	}
	
	/**
	 * 省(住址)
	 */
	public java.lang.String getAddressProvince() {
		return getStr("address_province");
	}
	
	/**
	 * 市(住址)
	 */
	public void setAddressCity(java.lang.String addressCity) {
		set("address_city", addressCity);
	}
	
	/**
	 * 市(住址)
	 */
	public java.lang.String getAddressCity() {
		return getStr("address_city");
	}
	
	/**
	 * 区县(住址)
	 */
	public void setAddressArea(java.lang.String addressArea) {
		set("address_area", addressArea);
	}
	
	/**
	 * 区县(住址)
	 */
	public java.lang.String getAddressArea() {
		return getStr("address_area");
	}
	
	/**
	 * 街道(住址)
	 */
	public void setAddressStreet(java.lang.String addressStreet) {
		set("address_street", addressStreet);
	}
	
	/**
	 * 街道(住址)
	 */
	public java.lang.String getAddressStreet() {
		return getStr("address_street");
	}
	
	/**
	 * 社区(住址)
	 */
	public void setAddressCommunity(java.lang.String addressCommunity) {
		set("address_community", addressCommunity);
	}
	
	/**
	 * 社区(住址)
	 */
	public java.lang.String getAddressCommunity() {
		return getStr("address_community");
	}
	
	/**
	 * 小区(住址)
	 */
	public void setAddressQuartersId(java.lang.String addressQuartersId) {
		set("address_quarters_id", addressQuartersId);
	}
	
	/**
	 * 小区(住址)
	 */
	public java.lang.String getAddressQuartersId() {
		return getStr("address_quarters_id");
	}
	
	/**
	 * 楼号(住址)
	 */
	public void setAddressFloor(java.lang.String addressFloor) {
		set("address_floor", addressFloor);
	}
	
	/**
	 * 楼号(住址)
	 */
	public java.lang.String getAddressFloor() {
		return getStr("address_floor");
	}
	
	/**
	 * 单元号(住址)
	 */
	public void setAddressUnit(java.lang.String addressUnit) {
		set("address_unit", addressUnit);
	}
	
	/**
	 * 单元号(住址)
	 */
	public java.lang.String getAddressUnit() {
		return getStr("address_unit");
	}
	
	/**
	 * 门牌号(住址)
	 */
	public void setAddressNumber(java.lang.String addressNumber) {
		set("address_number", addressNumber);
	}
	
	/**
	 * 门牌号(住址)
	 */
	public java.lang.String getAddressNumber() {
		return getStr("address_number");
	}
	
	/**
	 * 是否注册
	 */
	public void setIsResign(java.lang.String isResign) {
		set("is_resign", isResign);
	}
	
	/**
	 * 是否注册
	 */
	public java.lang.String getIsResign() {
		return getStr("is_resign");
	}
	
	/**
	 * 是否为网格员
	 */
	public void setIsGridUser(java.lang.String isGridUser) {
		set("is_grid_user", isGridUser);
	}
	
	/**
	 * 是否为网格员
	 */
	public java.lang.String getIsGridUser() {
		return getStr("is_grid_user");
	}
	
	/**
	 * 备用1
	 */
	public void setSpare1(java.lang.String spare1) {
		set("spare1", spare1);
	}
	
	/**
	 * 备用1
	 */
	public java.lang.String getSpare1() {
		return getStr("spare1");
	}
	
	/**
	 * 备用1
	 */
	public void setSpare2(java.lang.String spare2) {
		set("spare2", spare2);
	}
	
	/**
	 * 备用1
	 */
	public java.lang.String getSpare2() {
		return getStr("spare2");
	}
	
	/**
	 * 备用1
	 */
	public void setSpare4(java.lang.String spare4) {
		set("spare4", spare4);
	}
	
	/**
	 * 备用1
	 */
	public java.lang.String getSpare4() {
		return getStr("spare4");
	}
	
	/**
	 * 备用1
	 */
	public void setSpare3(java.lang.String spare3) {
		set("spare3", spare3);
	}
	
	/**
	 * 备用1
	 */
	public java.lang.String getSpare3() {
		return getStr("spare3");
	}
	
	/**
	 * 备用1
	 */
	public void setSpare5(java.lang.String spare5) {
		set("spare5", spare5);
	}
	
	/**
	 * 备用1
	 */
	public java.lang.String getSpare5() {
		return getStr("spare5");
	}
	
}
