package com.demo.common.model;

import com.demo.common.model.base.BaseAppUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUsers extends BaseAppUsers<AppUsers> {
	
}
